repos:
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.29.0
- hooks:
  - args:
    - --all
    - .
    id: pycln
    name: pycln
  repo: https://github.com/hadialqattan/pycln
  rev: v2.0.4
- hooks:
  - args:
    - --profile=black
    - .
    id: isort
    name: isort (python)
  repo: https://github.com/pycqa/isort
  rev: 5.10.1
- hooks:
  - id: black
  repo: https://github.com/psf/black
  rev: 22.6.0
- hooks:
  - args:
    - --recursive
    - src
    id: bandit
  repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
- hooks:
  - id: pip-audit
  repo: https://github.com/trailofbits/pip-audit
  rev: v2.4.2
- hooks:
  - id: trailing-whitespace
  - id: check-ast
  - id: check-json
  - id: check-toml
  - id: check-yaml
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
